# Shopify-hostad extension-only-app. Ingen extern server eller OAuth-callback.
client_id = "b13ce44f05cf46aeaff3976cd98b2723"
name = "hyllsektioner"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "write_products,read_metaobjects"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = []
